### PR TITLE
Some images has been further optimized.

### PR DESCRIPTION
**Pull request by adamradocz**
I further optimized some images and saved a few KBs
I used the FileOptimizer in lossless mode for the optimization.

### CODE REVIEW

**Comment by Peppernrino** [comment]
Care to post a log of what was changed? I won't absorb your commit like some people do... but it's good to keep a record for new users coming to the situation wondering what we did to the files. In particular, I know that the _ce.ico_ file was malformed by the ImageMagick tool in FileOptimizer. It has been removed from the .ico toolchain as a result of the artifacting: https://sourceforge.net/p/nikkhokkho/code/1406/

My example here: https://pastebin.com/MTtcVck2

Then I just have to try and figure out how to merge this into the other BOINC pull I've already done... I think I just click merge, right? I'm not super awesome at Github. lol

**Comment by adamradocz** [comment]
You can see the changes if you click on the Changes tab.

Yes, just click on  the merge button.

**Comment by Peppernrino** [comment]
I would like a log of the tools used, friend.

And after a quick download of the _ce.ico_ file, my suspicions have been confirmed... unfortunately it is broken. :( Make sure to visually confirm the integrity of files before submitting them. FileOptimizer is a great program, but it has quirks, like most programs. :)

**Comment by adamradocz** [comment]
I don't have the log, and I'm not sure the FileOptimizer is making any log.
You were right about the ICO files, I restored them.

**Comment by Peppernrino** [comment]
FileOptimizer has an option for logs. You would want level `4: Information`. Thank you for restoring the icon files. I'll get to this later this afternoon. :)

What happens if you run them again? Are we done the optimizations? lol

**Comment by adamradocz** [comment]
Yes, you'll get the same results.

**Comment by Peppernrino** [comment]
Sweet! Sorry for not reviewing/merging this yet, we got some unexpected company. :)

**Comment by Peppernrino** [comment]
My friend, I apologize for not getting to this in quick time. Took somewhat of a hiatus for my brain. Back and ready to go!

I'd say you honestly should just include your pull on top of mine on the BOINC repo if possible. I'm not good enough at Github right now. Don't trust myself to not break my pull. lol

**Comment by adamradocz** [comment]
I realized I made a mistake about deleting images so I closed the PR.

**Pull request closed without merging**
